# Service for the application
apiVersion: v1
kind: Service
metadata:
  name: firstapp
  labels:
    app: firstapp
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: firstapp
  type: ClusterIP
